<%@ page import="com.qysoft.rapid.utils.RenderHelper" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= RenderHelper.includedStyle(request, "/static/plugins/layui/css/layui.css") %>
    <%
        String ctx = request.getContextPath();
    %>
    <style>
    </style>
    <title>区域</title>
</head>
<body style="padding: 15px;">
<table class="layui-table">
    <colgroup>
        <col width="150">
        <col width="200">
        <col>
    </colgroup>
    <thead>
    <tr>
        <th>昵称</th>
        <th>加入时间</th>
        <th>签名</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>贤心</td>
        <td>2016-11-29</td>
        <td>人生就像是一场修行</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>许闲心</td>
        <td>2016-11-28</td>
        <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    <tr>
        <td>shenjinxiang</td>
        <td>2016-11-28</td>
        <td>123123123</td>
    </tr>
    </tbody>
</table>
<h1>shenjinxiang</h1>
<%=RenderHelper.includedJavascript(request, "/static/plugins/layui/layui.js") %>
<script>
//    parent.document.getElementById("external-frame").height=0;
//    parent.document.getElementById("external-frame").height=document.body.scrollHeight;
</script>
</body>
</html>